### PR TITLE
Update YaST/Repos/_openSUSE_Factory_Default.xml.in to handle aarch64 (boo#1120938)

### PR DESCRIPTION
**Pull request by ggardet**
And update translations

### CODE REVIEW

**Comment by lnussel** [comment]
the architectures attribute is handled where?

**Comment by ggardet** [comment]
> the architectures attribute is handled where?

It is a 1-click install feature: https://en.opensuse.org/openSUSE:One_Click_Install_specification

**Comment by ggardet** [comment]
> that's a different file than this one. I can't find any references in yast that would handle architectures here. You really need to put a second file next to the regular factory one

Which YaST module is it? Maybe adding the feature is not so hard?

**Comment by lnussel** [comment]
packager, check for external_sources_link

However, if you want to fix yast I'd probably put the arch tag on the url so one doesn't have to duplicate all texts.

**Comment by ggardet** [comment]
Closing as it seems that YaST does not support `arch` tag.
I will send another PR with another solution.

**Pull request closed without merging**
