### PR TITLE
Fix description of Tumbleweed's repositories

### PR DESCRIPTION
**Pull request by super7ramp**
Some descriptions of Tumbleweed's repositories contained references to 13.1 (and to Factory ;-)).

### CODE REVIEW

**Comment by coolo** [comment]
the update repo should actually be included. we use http://download.opensuse.org/repositories/openSUSE:/Factory:/Update/standard/  though

**Comment by coolo** [comment]
perhaps we can create an alias for that though to unconfuse people

**Comment by super7ramp** [comment]
OK, I've added it. There already is an alias, isn't it? http://download.opensuse.org/update/tumbleweed/

I'm not sure about the description though. I don't remember any updates from this repo since I started using Tumbleweed. It is intended for urgent updates, right?

**Comment by coolo** [comment]
ah, I tried without final / and it didn't work.

**Comment by coolo** [comment]
it is only for mega critical security updates

**Comment by super7ramp** [comment]
ok

**Pull request merged**
